### ISSUE TITLE
TLS protocol server mode error 

### ISSUE THREAD

**Issue by mortada-jafar** [komeilkma/Terminator-Samurai-VPN#13]
When using the TLS protocol in server mode, I encountered the following error :

```
2023/01/27 07:42:10 initialized config: &{DeviceName:enp1s LocalAddr::3000 ServerAddr::3001 ServerIP:172.18.0.1 ServerIPv6:fced:9999::1 DNSIP:8.8.8.8 CIDR:172.18.0.10/24 CIDRv6:fced:9999::9999/64 Key:12312300kma Protocol:tls WebSocketPath:/freedom ServerMode:true GlobalMode:false Obfs:false Compress:false MTU:1500 Timeout:30 LocalGateway: LocalGatewayv6: TLSCertificateFilePath: TLSCertificateKeyFilePath: TLSSni: TLSInsecureSkipVerify:false BufferSize:65536 Verbose:false}
2023/01/27 07:42:10 TSVPN tls server started on :3000
2023/01/27 07:42:10 open : no such file or directory
panic: open : no such file or directory

goroutine 16 [running]:
log.Panic({0xc00018ecc8?, 0x0?, 0x0?})
	C:/Program Files/Go/src/log/log.go:388 +0x65
github.com/komeilkma/Terminator-Samurai-VPN/tls.StartServer(_, {{0x7ffca39d1780, 0x5}, {0xba9888, 0x5}, {0xba988d, 0x5}, {0xbae10f, 0xa}, {0xbafb4e, ...}, ...})
	C:/Users/komeilkma/Music/Terminator-Samurai-VPN/tls/tlsserver.go:20 +0x18c
github.com/komeilkma/Terminator-Samurai-VPN/finalapp.(*App).StartApp(0xc000070580)
	C:/Users/komeilkma/Music/Terminator-Samurai-VPN/finalapp/final-app.go:60 +0x358
created by main.main
	C:/Users/komeilkma/Music/Terminator-Samurai-VPN/main.go:39 +0x7fb
```

**Comment by komeilkma** [comment]
I will investigate this problem and announce the result in the same issue thread
